### ISSUE TITLE
Website of Documentation not updated

### ISSUE THREAD

**Issue by al3xa23** [VILLASframework/Documentation#90]
Hi, 
I checked yesterday our documentation website and the changes from the last weekare not in there. 
Since the lat major change was beginning of the year and in the mean time only the CI was changed, I am not sure if it is caused by the CI change?

**Comment by stv0g** [comment]
Its strange, because the pipelines ran through:

https://git.rwth-aachen.de/acs/public/villas/documentation/-/jobs/5479084

**Comment by al3xa23** [comment]
Solved. Needed to add in kubernetes to latest tag.
